// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWurIygS_EQa5VLZfzBDkm66RK62eC63g',
    appId: '1:184869555067:web:70a878ad3c93440e1a4bde',
    messagingSenderId: '184869555067',
    projectId: 'otterside',
    authDomain: 'otterside.firebaseapp.com',
    storageBucket: 'otterside.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUNIxUqtkZACIsf4bwFgQ9I78MOFZdNVs',
    appId: '1:184869555067:android:00f50d30de6213041a4bde',
    messagingSenderId: '184869555067',
    projectId: 'otterside',
    storageBucket: 'otterside.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-p4OVsY2Fu9KIdk_TEeZ_TY0D7wqFmWM',
    appId: '1:184869555067:ios:f32ef14c17c582101a4bde',
    messagingSenderId: '184869555067',
    projectId: 'otterside',
    storageBucket: 'otterside.appspot.com',
    iosClientId: '184869555067-n3fs8e9m5npngch7v14nib64nte96ci1.apps.googleusercontent.com',
    iosBundleId: 'com.example.otterside',
  );
}
